DangHuy_TH3_Step_by_Step/Models/Book.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace DangHuy_TH3_Step_by_Step.Models
{
    public class Book
    {
        public int Id {  get; set; }
        public string Title { get; set; }
        public int AuthorId { get; set; }
        public int GenreId { get; set; }
        public string Image {  get; set; }

        public float Price { get; set; }    
        public int TotalPage { get; set; }

        public string Sumary { get; set; }

        public List<Book> GetBookList()
        {
            List<Book> books = new List<Book>()
            {
                new Book()
                {
                    Id = 1,
                    Title = "Chí Phèo",
                    AuthorId = 1,
                    GenreId = 1,
                    Image = "/images/products/b1.jpg",
                    Price = 500000,
                    Sumary = "",
                    TotalPage = 250
                },
                new Book()
                {
                    Id = 2,
                    Title = "Lão hạc",
                    AuthorId = 1,
                    GenreId = 1,
                    Image = "/images/products/b2.jpg",
                    Price = 600000,
                    Sumary = "",
                    TotalPage = 240
                },
                new Book()
                {
                    Id = 3,
                    Title = "Conan phiêu lưu ký",
                    AuthorId = 1,
                    GenreId = 1,
                    Image = "/images/products/b3.jpg",
                    Price = 200000,
                    Sumary = "",
                    TotalPage = 140
                },
                new Book()
                {
                    Id = 4,
                    Title = "Đường xưa mây trắng",
                    AuthorId = 1,
                    GenreId = 1,
                    Image = "/images/products/b4.jpg",
                    Price = 300000,
                    Sumary = "",
                    TotalPage = 400
                }
            };
            return books;
        }

        public Book GetBookById(int id)
        {
            Book book = this.GetBookList().FirstOrDefault(b => b.Id == id);
            return book;
        }

        public List<SelectListItem> Authors { get; } = new List<SelectListItem>
        {
            new SelectListItem {Value = "1",Text = "Nam Cao"},
            new SelectListItem {Value = "2",Text = "Ngô Tất Tố" },
            new SelectListItem {Value = "3",Text = "Adamkhoom" },
            new SelectListItem {Value = "4",Text = "Thiền sư Thích Nhất Hạnh"}
        };

        public List<SelectListItem> Genres { get; } = new List<SelectListItem>
        {
            new SelectListItem {Value = "1",Text = "Truyện tranh" },
            new SelectListItem {Value = "2",Text = "Văn học đương đại" },
            new SelectListItem {Value = "3",Text = "Phật học phổ thông"},
            new SelectListItem {Value = "4",Text = "Truyện cười"}
        };

    }
}

DangHuy_TH3_Step_by_Step/Models/ErrorViewModel.cs
namespace DangHuy_TH3_Step_by_Step.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DangHuy_TH3_Step_by_Step/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using DangHuy_TH3_Step_by_Step.Models;
namespace DangHuy_TH3_Step_by_Step.Controllers
{
    public class BookController : Controller
    {
        protected Book book = new Book();
        public IActionResult Index()
        {
            ViewBag.authors = book.Authors;
            ViewBag.genres = book.Genres;
            var books = book.GetBookList();
            return View(books);
        }
        public IActionResult Create()
        {
            ViewBag.authors = book.Authors;
            ViewBag.genres = book.Genres;
            Book model = new Book();
            return View(model);
        }
        public IActionResult Edit(int id)
        {
            ViewBag.authors = book.Authors;
            ViewBag.Genres = book.Genres;
            Book model = book.GetBookById(id);
            return View(model);
        }
        public PartialViewResult PopularBook()
        {
            var books = book.GetBookList();
            return PartialView(books);
        }
    }


}

DangHuy_TH3_Step_by_Step/Controllers/HomeController.cs
using System.Diagnostics;
using DangHuy_TH3_Step_by_Step.Models;
using Microsoft.AspNetCore.Mvc;

namespace DangHuy_TH3_Step_by_Step.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DangHuy_TH3_Step_by_Step/ViewComponents/BookViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using DangHuy_TH3_Step_by_Step.Models;

namespace DangHuy_TH3_Step_by_Step.ViewComponents
{
    public class BookViewComponent : ViewComponent
    {
        protected Book book = new Book();
        public IViewComponentResult Invoke()
        {
            var books = book.GetBookList();
            return View(books);
        }
    }
}

DangHuy_TH3_Step_by_Step/Views/Book/Create.cshtml
@model DangHuy_TH3_Step_by_Step.Models.Book

@{
    ViewData["Title"] = "Create";
}
<h2>Thêm mới sách</h2>
<form action="" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title">Tên sách</label>
        <input type="text" class="form-control" asp-for="Title" placeholder="Tên sách" />
    </div>  
    <div class="form-group">
        <label asp-for="AuthorId">Tác giả</label>
        <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.authors">
            <option value="">Chọn tác giả</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="GenreId">Thể loại</label>
        <select asp-for="GenreId" class="form-control" asp-items="ViewBag.genres">
            <option value="">Chọn Thể loại</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Price">Giá sách</label>
        <input asp-for="Price" class="form-control" placeholder="Giá sách" />
    </div>

    <div class="form-group">
        <label asp-for="TotalPage">Tổng số trang</label>
        <input asp-for="TotalPage" class="form-control" placeholder="Tổng số trang" />
    </div>

    <div class="form-group">
        <label asp-for="Image">Hình ảnh / Poster</label>
        <input asp-for="Image" type="file" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Sumary">Giới thiệu ngắn</label>
        <textarea asp-for="Sumary" class="form-control" placeholder="Nội dung giới thiệu sách..."></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Lưu lại</button>
</form>

DangHuy_TH3_Step_by_Step/Views/Book/Edit.cshtml
@model DangHuy_TH3_Step_by_Step.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h2>Chỉnh sửa sách</h2>

<form action="" method="POST" role="form">
    <div class="form-group">
        <label asp-for="Title">Tên sách</label>
        <input type="text" class="form-control" asp-for="Title" placeholder="Tên sách" />
    </div>

    <div class="form-group">
        <label asp-for="AuthorId">Tác giả</label>
        <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.authors">
            <option value="">Chọn tác giả</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="GenreId">Thể loại</label>
        <select asp-for="GenreId" class="form-control" asp-items="ViewBag.genres">
            <option value="">Chọn Thể loại</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Price">Giá sách</label>
        <input type="text" class="form-control" asp-for="Price" placeholder="Giá sách" />
    </div>

    <div class="form-group">
        <label asp-for="TotalPage">Tổng số trang</label>
        <input type="text" class="form-control" asp-for="TotalPage" placeholder="Tổng số trang" />
    </div>

    <div class="form-group">
        <label asp-for="Image">Hình ảnh / Poster</label>
        <input type="file" class="form-control" asp-for="Image" />
    </div>

    <div class="form-group">
        <label asp-for="Sumary">Giới thiệu ngắn</label>
        <textarea class="form-control" asp-for="Sumary" placeholder="Nội dung giới thiệu sách..."></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Lưu lại</button>
</form>

DangHuy_TH3_Step_by_Step/Views/Book/Index.cshtml
@model IEnumerable<DangHuy_TH3_Step_by_Step.Models.Book>
@{
	ViewData["Title"] = "Index";

}
<h2> Danh sách các cuốn sách </h2>
<!--Hiểnt hị các comboobox trên form-->
<form action = "" method="post" class="form-inline" role="form">
	<div class="form-group">
		<select name="AuthorId" class="form-control" asp-items="@ViewBag.authors">
			<option value="">Chọn tác giả</option>
		</select>
		<select name="GenreId" class="form-control" asp-items="@ViewBag.genres">
			<option value ="">Chọn thể loại</option>

		</select>

	</div>
	<button type="submit" class="btn btn-primary">Tìm kiếm</button>
	<a asp-action="Create" class="btn btn-danger">Thêm mới</a>
</form>
<hr/>

<!--Hiển thị các sách-->
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Id</th>
			<th>Tiêu đề</th>
			<th>Tác giả</th>
			<th>Thể loại</th>
			<th>Giá</th>
			<th>Hình ảnh</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var book in Model)
		{
			<tr>
				<td>@book.Id</td>
				<td>@book.Title</td>
				<td>@book.AuthorId</td>
				<td>@book.GenreId</td>
				<td>@book.Price</td>
				<td>
					<img src ="@book.Image" alt="@book.Title" width="40" />
				</td>

				<td>
					<a asp-action="Edit" asp-route-id="@book.Id" class="btn tbn-sm btn-primary">Sửa</a>
				</td>
			</tr>
		}
	</tbody>
</table>

DangHuy_TH3_Step_by_Step/Views/Book/PopularBook.cshtml
@model IEnumerable<DangHuy_TH3_Step_by_Step.Models.Book>
@foreach (var item in Model)
{
	<div class ="col-xs-3 col-sm-3 col-md-3 col-lg-3">
		<div class = "thumbnail">
			<img src ="@item.Image" alt="" />
			<div class="caption">
				<h3>@item.Title</h3>
				<p>
					Price : @item.Price
				</p>
			</div>
		</div>
	</div>
}
<style>
	.thumbnail img {
		width: 100%; 
		height: 400px; 
		object-fit: cover; 
		border-radius: 5px; 
	}
</style>

DangHuy_TH3_Step_by_Step/Views/Shared/Banner.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DangHuy_TH3_Step_by_Step/Views/Shared/Components/Book/Default.cshtml
@model IEnumerable<DangHuy_TH3_Step_by_Step.Models.Book>
<div class="row">
	@foreach (var item in Model)
	{
		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
			<div class="thumbnail">
				<img src="@item.Image" alt="" />
				<div class="caption">
					<h3>@item.Title</h3>
					<p>
						Price : @item.Price
					</p>
				</div>
			</div>
		</div>
	}
</div>

<style>
	.thumbnail img {
		width: 100%;
		height: 400px;
		object-fit: cover;
		border-radius: 5px;
	}
</style>

DangHuy_TH3_Step_by_Step/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DangHuy_TH3_Step_by_Step</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DangHuy_TH3_Step_by_Step.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DangHuy_TH3_Step_by_Step</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DangHuy_TH3_Step_by_Step - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DangHuy_TH3_Step_by_Step/Views/Shared/my_layout.cshtml
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>.NET CORE 2.x - @ViewBag.Title</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">.NET CORE 2.x</a>
            <ul class="nav navbar-nav">
                <li class="active"><a asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                <li><a asp-controller="Home" asp-action="About">Giới thiệu</a></li>
                <li><a asp-controller="Home" asp-action="Contact">Liên hệ</a></li>
                <li><a asp-controller="Book" asp-action="Index">Sách</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
         @RenderBody()
     </div>
     <!-- jQuery -->
     <script src="https://code.jquery.com/jquery.min.js"></script>
     <!-- Bootstrap JavaScript -->
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     @RenderSection("Scripts", required: false)
</body>
</html>